name: Playwright tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install playwright fully
        run: npx playwright install

      - name: Run tests
        run: npm run test:integration
