name: Playwright tests

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install playwright browsers
        run: npx playwright install && npx playwright install-deps

      - name: Run tests
        run: DISCORD_WEBHOOK=${{ env.DISCORD_WEBHOOK }} VITE_ACKEE_DOMAIN=${{ env.VITE_ACKEE_DOMAIN }} VITE_ACKEE_ACTION__REACHED_CONTACT=${{ env.VITE_ACKEE_ACTION__REACHED_CONTACT }} npm run test
